// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VillaMagica_API.Datos;

#nullable disable

namespace VillaMagica_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VillaMagica_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Fernando",
                            FechaActualizacion = new DateTime(2024, 2, 29, 16, 43, 43, 567, DateTimeKind.Local).AddTicks(4269),
                            FechaCreacion = new DateTime(2024, 2, 29, 16, 43, 43, 567, DateTimeKind.Local).AddTicks(4257),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Casitas",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Mont",
                            FechaActualizacion = new DateTime(2024, 2, 29, 16, 43, 43, 567, DateTimeKind.Local).AddTicks(4272),
                            FechaCreacion = new DateTime(2024, 2, 29, 16, 43, 43, 567, DateTimeKind.Local).AddTicks(4272),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "navarro",
                            Ocupantes = 10,
                            Tarifa = 1200.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
